<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Authors>Iluay</Authors>
        <Version>0.1.2.0</Version>
        <Description>In-game DPS meter and fight history.</Description>
        <PackageProjectUrl>https://github.com/Iluay0/studium</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Studium.Core\Studium.Core.csproj" />
    </ItemGroup>
</Project>
